ignore:
  - "components"
  - "packages/stickyroll"
  - "packages/decorators"
  - "packages/utils/scr/scroll-to.ts"
  - "packages/utils/scr/throttle.ts"
  - "src/tracker"
  - "src/context"
  - "**/test"
